[package]
name = "soonscan"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
crossterm = "0.28.1"
ratatui = "0.29.0"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0.133"
tokio = { version = "1", features = ["full"] }

